version: '3'
services:
  postgresql:
    image: postgres
    container_name: lesson
    ports:
      - "5435:5432"
    environment: 
      - POSTGRES_USER=lesson
      - POSTGRES_PASSWORD=lesson
      - POSTGRES_DB=lesson 
    command: postgres
    restart: always
  
  redis:
    image: redis:alpine3.14 
    container_name: redis-lesson
    ports:
      - "6379:6379"