export const users = [
    {
        _id: '667a92a2267fc739ac592ecf',
        index: 0,
        guid: 'bc080e48-24c6-4b40-9e1a-2ba5a5e90bf5',
        isActive: false,
        balance: '$1,024.17',
        picture: 'http://placehold.it/32x32',
        age: 26,
        eyeColor: 'brown',
        name: 'Corrine Petty',
        gender: 'female',
        company: 'ZAGGLES',
        email: 'corrinepetty@zaggles.com',
        phone: '+1 (995) 575-2383',
        address: '439 Hancock Street, Maplewood, South Dakota, 7647',
        about:
            'Minim irure et aute nisi Lorem. Ad cillum aliquip sint ex dolor do enim deserunt anim deserunt elit ut quis. Deserunt amet id amet aliqua aliqua eu consequat reprehenderit ut consectetur tempor reprehenderit sit aliquip. Occaecat ad commodo commodo Lorem. Ea culpa eu aliqua esse nulla reprehenderit pariatur minim aliqua. Ea non labore officia adipisicing sit amet consectetur et enim.\r\n',
        registered: '2022-04-29T11:05:43 -02:00',
        latitude: 37.572495,
        longitude: -73.80829,
        tags: [
            'laborum',
            'incididunt',
            'do',
            'quis',
            'reprehenderit',
            'nostrud',
            'duis',
        ],
        friends: [
            {
                id: 0,
                name: 'Tricia Price',
            },
            {
                id: 1,
                name: 'Estes Watson',
            },
            {
                id: 2,
                name: 'Villarreal Bush',
            },
        ],
        greeting: 'Hello, Corrine Petty! You have 4 unread messages.',
        favoriteFruit: 'apple',
    },
    {
        _id: '667a92a20649f94b9162f6aa',
        index: 1,
        guid: '7b4a15c5-8154-4afa-8961-33b0629d3948',
        isActive: false,
        balance: '$2,882.46',
        picture: 'http://placehold.it/32x32',
        age: 21,
        eyeColor: 'blue',
        name: 'Sharon May',
        gender: 'female',
        company: 'TALKOLA',
        email: 'sharonmay@talkola.com',
        phone: '+1 (877) 416-2295',
        address: '667 Henry Street, Allentown, Florida, 1028',
        about:
            'Minim proident mollit ut et fugiat elit. Commodo mollit mollit fugiat in laborum dolor do et laboris magna irure. Dolore irure reprehenderit aute ea commodo consequat. Elit reprehenderit id adipisicing id elit mollit laborum aute Lorem. Aliqua nulla cupidatat tempor consectetur consequat elit est. Cupidatat eiusmod laboris sunt anim sit sit amet anim dolore et ipsum ad velit.\r\n',
        registered: '2019-04-02T08:17:25 -02:00',
        latitude: 40.603276,
        longitude: -28.403808,
        tags: ['veniam', 'ipsum', 'qui', 'adipisicing', 'sunt', 'eu', 'incididunt'],
        friends: [
            {
                id: 0,
                name: 'Lawanda Case',
            },
            {
                id: 1,
                name: 'Willie Calderon',
            },
            {
                id: 2,
                name: 'Bethany Cochran',
            },
        ],
        greeting: 'Hello, Sharon May! You have 6 unread messages.',
        favoriteFruit: 'banana',
    },
    {
        _id: '667a92a2e106ce808bcf4f4d',
        index: 2,
        guid: '1fb36dc8-628d-438d-b605-478a3ee2a0ac',
        isActive: true,
        balance: '$1,250.70',
        picture: 'http://placehold.it/32x32',
        age: 21,
        eyeColor: 'brown',
        name: 'Maxwell Combs',
        gender: 'male',
        company: 'TALKALOT',
        email: 'maxwellcombs@talkalot.com',
        phone: '+1 (811) 528-3704',
        address: '713 Sutter Avenue, Katonah, Ohio, 6397',
        about:
            'Laborum aliquip dolor mollit nulla magna cillum amet. Sunt non duis nulla non non culpa. Nostrud anim incididunt dolore reprehenderit qui exercitation quis velit aliquip culpa enim reprehenderit aliqua velit.\r\n',
        registered: '2015-01-15T04:15:23 -01:00',
        latitude: 46.137947,
        longitude: -41.759174,
        tags: ['adipisicing', 'laborum', 'anim', 'culpa', 'officia', 'nisi', 'id'],
        friends: [
            {
                id: 0,
                name: 'Anne Gardner',
            },
            {
                id: 1,
                name: 'Kimberly Bryant',
            },
            {
                id: 2,
                name: 'Santos Rowe',
            },
        ],
        greeting: 'Hello, Maxwell Combs! You have 8 unread messages.',
        favoriteFruit: 'strawberry',
    },
    {
        _id: '667a92a2240e939303d520f4',
        index: 3,
        guid: '6f986504-22d5-43d5-bcf2-3f4f6654c84b',
        isActive: false,
        balance: '$1,201.65',
        picture: 'http://placehold.it/32x32',
        age: 22,
        eyeColor: 'green',
        name: 'Carney Hunter',
        gender: 'male',
        company: 'COMVENE',
        email: 'carneyhunter@comvene.com',
        phone: '+1 (974) 500-3624',
        address: '610 Rutland Road, Sharon, Idaho, 5672',
        about:
            'Excepteur est ex consequat consequat enim sunt consequat. Do minim consequat nostrud ex fugiat adipisicing ullamco consectetur aute consequat aliqua do. Eu et magna exercitation labore fugiat.\r\n',
        registered: '2020-02-22T03:13:12 -01:00',
        latitude: -73.15133,
        longitude: -177.753576,
        tags: ['nostrud', 'ad', 'fugiat', 'ipsum', 'in', 'ut', 'ut'],
        friends: [
            {
                id: 0,
                name: 'Albert Clarke',
            },
            {
                id: 1,
                name: 'Muriel Alford',
            },
            {
                id: 2,
                name: 'Kerry Rodriguez',
            },
        ],
        greeting: 'Hello, Carney Hunter! You have 9 unread messages.',
        favoriteFruit: 'banana',
    },
    {
        _id: '667a92a2460708c09221efce',
        index: 4,
        guid: '1946b6f4-39ad-468d-ac19-9a19a8d9a082',
        isActive: true,
        balance: '$1,714.50',
        picture: 'http://placehold.it/32x32',
        age: 32,
        eyeColor: 'blue',
        name: 'Tina Parks',
        gender: 'female',
        company: 'FROSNEX',
        email: 'tinaparks@frosnex.com',
        phone: '+1 (958) 570-3528',
        address: '246 Clarkson Avenue, Munjor, Palau, 132',
        about:
            'Consequat laborum culpa eu consequat enim id Lorem fugiat est officia irure amet officia. Nulla excepteur labore velit dolor aute sint esse nulla magna sint. Ea nostrud incididunt eiusmod ullamco esse eu consectetur anim aute commodo exercitation cillum labore.\r\n',
        registered: '2020-02-15T12:50:14 -01:00',
        latitude: -3.750147,
        longitude: -73.181407,
        tags: [
            'nulla',
            'consequat',
            'ex',
            'magna',
            'reprehenderit',
            'occaecat',
            'laborum',
        ],
        friends: [
            {
                id: 0,
                name: 'Stout Whitney',
            },
            {
                id: 1,
                name: 'Parrish Dodson',
            },
            {
                id: 2,
                name: 'Willa Black',
            },
        ],
        greeting: 'Hello, Tina Parks! You have 8 unread messages.',
        favoriteFruit: 'banana',
    },
    {
        _id: '667a92a23f3e7d5f1552bc6b',
        index: 5,
        guid: '30cdff9c-5ac1-4301-b9b4-5b6b315aada4',
        isActive: true,
        balance: '$3,382.42',
        picture: 'http://placehold.it/32x32',
        age: 34,
        eyeColor: 'green',
        name: 'Cummings Dennis',
        gender: 'male',
        company: 'AVIT',
        email: 'cummingsdennis@avit.com',
        phone: '+1 (843) 568-2344',
        address: '921 Stryker Court, Robinette, Puerto Rico, 2680',
        about:
            'Qui occaecat laborum eiusmod cillum excepteur laborum eiusmod reprehenderit. Fugiat pariatur nostrud deserunt ea aliqua velit ullamco proident nulla. Deserunt commodo ea in est aute cillum aliquip in id magna. Dolor excepteur pariatur irure velit. Commodo duis reprehenderit dolor aliquip. Reprehenderit cillum consequat nisi voluptate voluptate ut labore nisi nulla tempor laboris nulla.\r\n',
        registered: '2016-08-14T11:52:05 -02:00',
        latitude: 50.525936,
        longitude: -172.515866,
        tags: ['ut', 'non', 'do', 'ut', 'magna', 'enim', 'laboris'],
        friends: [
            {
                id: 0,
                name: 'Pace Griffin',
            },
            {
                id: 1,
                name: 'Bender Burgess',
            },
            {
                id: 2,
                name: 'Shauna Mathis',
            },
        ],
        greeting: 'Hello, Cummings Dennis! You have 1 unread messages.',
        favoriteFruit: 'banana',
    },
    {
        _id: '667a92a2062263b35986aa46',
        index: 6,
        guid: '9c2241ff-b393-4631-bf56-d70193d5e52f',
        isActive: true,
        balance: '$2,165.76',
        picture: 'http://placehold.it/32x32',
        age: 31,
        eyeColor: 'green',
        name: 'Hyde Valenzuela',
        gender: 'male',
        company: 'KNOWLYSIS',
        email: 'hydevalenzuela@knowlysis.com',
        phone: '+1 (887) 432-3707',
        address: '528 Haring Street, Harrison, American Samoa, 9228',
        about:
            'Nostrud et do Lorem velit dolor minim deserunt culpa irure mollit aliquip. Fugiat culpa reprehenderit amet amet magna in amet proident ullamco consectetur proident sit ex. Ullamco excepteur laboris id dolor est minim sit. Elit minim cupidatat fugiat in qui sit sint ex. Mollit do ea id ad nostrud mollit duis irure irure ullamco magna labore.\r\n',
        registered: '2023-03-01T10:23:58 -01:00',
        latitude: -19.215536,
        longitude: -126.04453,
        tags: ['fugiat', 'id', 'do', 'qui', 'anim', 'nisi', 'fugiat'],
        friends: [
            {
                id: 0,
                name: 'King Huffman',
            },
            {
                id: 1,
                name: 'Caroline Bowers',
            },
            {
                id: 2,
                name: 'Dixon Kane',
            },
        ],
        greeting: 'Hello, Hyde Valenzuela! You have 9 unread messages.',
        favoriteFruit: 'apple',
    },
];
